Chain link implementation
dial-once/node-logtify-logstash pull request #1
Opened 2017-05-25 08:39 UTC by Spring3

2017-05-30 07:56 UTC, jkernech requested changes

2017-05-30 07:56 UTC, jkernech commented on src/index.js
> +      host: 'logstash.dialonce.net'
Those values should be customisable via environment variables

2017-05-30 08:53 UTC, Spring3 commented on src/index.js
> +      host: 'logstash.dialonce.net'
Oh, yes, thanks. I totally forgot to move them to envs

2017-05-30 10:10 UTC, mrister commented on README.md
> +# logtify-logstash
would be nice to add some badges to the readme.

2017-05-30 10:14 UTC, mrister approved these changes

2017-05-30 10:14 UTC, mrister commented on package.json
> +  "dependencies": {
Minor: make dependencies appear before in the package.json than devDeps.

2017-05-30 10:14 UTC, mrister commented on src/index.js
> +      console.warn('Logstash logging was not initialized due to a missing token');
there is a token for logstash ?

2017-05-30 13:42 UTC, jkernech commented on src/index.js
> +      console.warn('Logstash logging was not initialized due to a missing token');
Nope there is no token, the message needs to be updated

2017-05-31 14:29 UTC, jkernech requested changes
Agree with the small adjustments proposed by Mihovil, on the other hand the error message needs to be fixed

2017-06-29 09:47 UTC, mrister approved these changes

2017-06-30 12:39 UTC, ofkindness approved these changes

2017-07-03 17:40 UTC, jkernech approved these changes
@Spring3 ⚡️ 
Please go ahead and merge this one

2017-07-03 19:08 UTC, merged